#!/bin/bash

clear
echo -e "================================================="
echo -e "#       Premium Auto Script By KEK BURUK        #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# VPN-BUDAKGERIK PREMIUM                        #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# ALLAH SWT                                     #"
echo -e "# vpn-budakgerik@gmail.com                      #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# And also for All my friend                    #"
echo -e "#                                               #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
