#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
PURPLE='\033[0;35m'

clear
echo -e ""
echo -e "=============================-Menu-============================="
echo -e "${green}      PREMIUM VPS SCRIPT BY AKUBUDAKGERIK${NC}"
echo -e ""
echo -e "${green}=========================-SSH & OpenVPN-========================${NC}"
echo -e "$PURPLE •1 $NC     : ${green}Create SSH & OpenVPN Account${NC}"
echo -e "$PURPLE •2 $NC     : ${green}Generate SSH & OpenVPN Trial Account${NC}"
echo -e "$PURPLE •3 $NC     : ${green}Extending SSH & OpenVPN Account Active Life${NC}"
echo -e "$PURPLE •4 $NC     : ${green}Delete SSH & OpenVPN Account${NC}"
echo -e "$PURPLE •5 $NC     : ${green}Check User Login SSH & OpenVPN${NC}"
echo -e "$PURPLE •6 $NC     : ${green}Daftar Member SSH & OpenVPN${NC}"
echo -e "$PURPLE •7 $NC     : ${green}Delete User Expired SSH & OpenVPN${NC}"
echo -e "$PURPLE •8 $NC     : ${green}Set up Autokill SSH${NC}"
echo -e "$PURPLE •9 $NC     : ${green}Displays Users Who Do Multi Login SSH${NC}"
echo -e "$PURPLE 10 $NC     : ${green}Restart Service Dropbear, Squid3, OpenVPN dan SSH${NC}"
echo -e ""
echo -e "${green}===========================-Wireguard-=========================${NC}"
echo -e "* add-wg       : Create Wireguard Account"
echo -e "* del-wg       : Delete Wireguard Account"
echo -e "* cek-wg       : Check User Login Wireguard"
echo -e "* renew-wg     : Extending Wireguard Account Active Life"
echo -e "* wg show      : Check Wireguard User Interface"
echo -e ""
echo -e "${green}=============================-L2TP-============================${NC}"
echo -e "* add-l2tp     : Creating L2TP Account"
echo -e "* del-l2tp     : Deleting L2TP Account"
echo -e "* renew-l2tp   : Extending L2TP Account Active Life"
echo -e ""
echo -e "${green}=============================-PPTP-============================${NC}"
echo -e "* add-pptp     : Create Account PPTP"
echo -e "* del-pptp     : Delete PPTP Account"
echo -e "* renew-pptp   : Extending PPTP Account Active Life"
echo -e "* cek-pptp     : Check User Login PPTP"
echo -e ""
echo -e "${green}=============================-SSTP-============================${NC}"
echo -e "* add-sstp     : Create Account SSTP"
echo -e "* del-sstp     : Delete SSTP Account"
echo -e "* renew-sstp   : Extending SSTP Account Active Life"
echo -e "* cek-sstp     : Check User Login SSTP"
echo -e ""
echo -e "${green}=============================-SSR-=============================${NC}"
echo -e "* add-ssr      : Create SSR Account"
echo -e "* del-ssr      : Deleting SSR Account"
echo -e "* renew-ssr    : Extending SSR Account Active Life"
echo -e "* ssr          : Show Other SSR Menu"
echo -e ""
echo -e "${green}========================-Shadowsocks OBFS-=====================${NC}"
echo -e "* add-ss       : Creating Shadowsocks Account"
echo -e "* del-ss       : Delete Shadowsocks Account"
echo -e "* renew-ss     : Extending Shadowsocks Account Active Life"
echo -e "* cek-ss       : Check User Login Shadowsocks"
echo -e ""
echo -e "${green}=============================-VMESS-===========================${NC}"
echo -e "* add-ws       : Create V2RAY Vmess Websocket Account"
echo -e "* del-ws       : Deleting V2RAY Vmess Websocket Account"
echo -e "* renew-ws     : Extending Vmess Account Active Life"
echo -e "* cek-ws       : Check User Login V2RAY"
echo -e "* cert2vray    : Renew Certificate V2RAY Account"
echo -e ""
echo -e "${green}=============================-VLESS-===========================${NC}"
echo -e "* add-vless    : Create V2RAY Vless Websocket Account"
echo -e "* del-vless    : Deleting V2RAY Vless Websocket Account"
echo -e "* renew-vless  : Extending Vless Account Active Life"
echo -e "* cek-ws       : Check User Login V2RAY"
echo -e ""
echo -e "${green}=============================-Trojan-==========================${NC}"
echo -e "* add-tr       : Create Trojan Account"
echo -e "* del-tr       : Deleting Trojan Account"
echo -e "* renew-tr     : Extending Trojan Account Active Life"
echo -e "* cek-tr       : Check User Login Trojan"
echo -e ""
echo -e "${green}=============================-SYSTEM-==========================${NC}"
echo -e "* add-host     : Add Or Change Subdomain Host For VPS"
echo -e "* change-port  : Change Port Of Some Service"
echo -e "* autobackup   : Autobackup Data VPS"
echo -e "* backup       : Backup Data VPS"
echo -e "* restore      : Restore Data VPS"
echo -e "* wbmn         : Webmin Menu"
echo -e "* kernel-updt  : Update To Latest Kernel"
echo -e "* limit-speed  : Limit Bandwith Speed Server"
echo -e "* ram          : Check Usage of VPS Ram"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Speedtest VPS"
echo -e "* update       : Update To Latest Script Version"
echo -e "* info         : Displaying System Information"
echo -e "* about        : Info Script Auto Install"
echo -e "* exit         : Exit From VPS "
echo -e ""
echo -e "${green}===============================================================${NC}"
echo -e ""
